---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	model(model)
	tools(tools)
	ContentFilterMiddleware\2ebefore_agent(ContentFilterMiddleware.before_agent)
	PIIMiddleware\5bemail\5d\2ebefore_model(PIIMiddleware[email].before_model)
	PIIMiddleware\5bemail\5d\2eafter_model(PIIMiddleware[email].after_model)
	HumanInTheLoopMiddleware\2eafter_model(HumanInTheLoopMiddleware.after_model)
	SafetyGuardrailMiddleware\2eafter_agent(SafetyGuardrailMiddleware.after_agent)
	__end__([<p>__end__</p>]):::last
	ContentFilterMiddleware\2ebefore_agent -.-> PIIMiddleware\5bemail\5d\2ebefore_model;
	ContentFilterMiddleware\2ebefore_agent -.-> SafetyGuardrailMiddleware\2eafter_agent;
	HumanInTheLoopMiddleware\2eafter_model --> PIIMiddleware\5bemail\5d\2eafter_model;
	PIIMiddleware\5bemail\5d\2eafter_model -.-> PIIMiddleware\5bemail\5d\2ebefore_model;
	PIIMiddleware\5bemail\5d\2eafter_model -.-> SafetyGuardrailMiddleware\2eafter_agent;
	PIIMiddleware\5bemail\5d\2eafter_model -.-> tools;
	PIIMiddleware\5bemail\5d\2ebefore_model -.-> SafetyGuardrailMiddleware\2eafter_agent;
	PIIMiddleware\5bemail\5d\2ebefore_model -.-> model;
	SafetyGuardrailMiddleware\2eafter_agent -.-> __end__;
	__start__ --> ContentFilterMiddleware\2ebefore_agent;
	model --> HumanInTheLoopMiddleware\2eafter_model;
	tools -.-> PIIMiddleware\5bemail\5d\2ebefore_model;
	SafetyGuardrailMiddleware\2eafter_agent -.-> SafetyGuardrailMiddleware\2eafter_agent;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

