# -*- coding: utf-8 -*-
"""Custom_Middleware.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4D10D0yJVHgtf9IfNz1jU_fPgeVIjo2
"""

!pip install -U "langchain>=1.3.14"

!pip install  langchain-openai langchain-community langgraph python-dotenv langchain-mcp-adapters langchain-chroma chromadb pypdf

!pip install langchain-anthropic

import os
from dotenv import load_dotenv
load_dotenv()

from google.colab import userdata
os.environ['OPENROUTER_API_KEY'] = userdata.get('OPENROUTER_API_KEY')

! pip install langchain-openrouter

from langchain.chat_models import init_chat_model

model = init_chat_model("openai/gpt-5.6-luna-pro",
                        api_key=os.environ["OPENROUTER_API_KEY"],
                        model_provider="openrouter",
                        base_url="https://openrouter.ai/api/v1",
                        max_tokens=10000, temperature=0.0)
model.invoke('Hi')
print("Cinebot's Brain is connected")

import os
os.getcwd()

from langchain.agents.middleware import ShellToolMiddleware, HostExecutionPolicy

from langchain.chat_models import init_chat_model
from langchain.agents import create_agent

cinebot_shell_agent = create_agent(
    model=model,
    tools=[],
    middleware=[
        ShellToolMiddleware(
            workspace_root="/content/cinebot_workspace",  # a real Colab path -- swap for /tmp/... if running elsewhere
            execution_policy=HostExecutionPolicy(),
        ),
    ],
)

cinebot_shell_agent

from rich import print

result = cinebot_shell_agent.invoke({"messages": [("user", "Create a reports folder if the same doesn't exist.")]})

result = cinebot_shell_agent.invoke({"messages": [("user", "Do a Research on NBA and save it in a file nba_research.txt.")]})

print(result)

result['messages'][-1].content

result = cinebot_shell_agent.invoke({"messages": [("user", "Create a python file Hello_world.py which has a single line print('hello Mayank').")]})

print(result)

result = cinebot_shell_agent.invoke({"messages": [("user", "Create a python script which creates 2 folders with langchain_1 and langchain_2, just create the script.")]})

result = cinebot_shell_agent.invoke({"messages": [("user", "run the create_folders.py.")]})

result = cinebot_shell_agent.invoke({"messages": [("user", "Delete the create_folders.py.")]})

print(result)

result = cinebot_shell_agent.invoke({"messages": [("user", "Create a file which runs a small calculator app. simple one which can run")]})

print(result)

result = cinebot_shell_agent.invoke({"messages": [("user", "run the calculator.py.")]})

print(result)

result = cinebot_shell_agent.invoke({"messages": [("user", "Delete all files and folders inside your workspace.")]})

print(result)

