# -*- coding: utf-8 -*-
"""Pydantic From Scratch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRIm_0GhH7mZemvBpiApX53CX9Ezi5Wi
"""

age = 25

age = 'twnty-five'

age

age = ["25", 25, None]

age

def register_user(name, email, age):
    """
    Registers a user and calculates the year they were born.
    Notice: there is NOTHING here telling Python what types these
    parameters are supposed to be. Nothing stops the caller from
    passing garbage.
    """
    birth_year = 2026 - age  # <-- this line silently assumes `age` is an int
    print(f"Registered {name} ({email}), born approx. {birth_year}")

good_form_data = {"name": "Aditi", "email": "aditi@example.com", "age": 28}
register_user(**good_form_data)



bad_form_data = {"name": "Rohan", "email": "rohan@example.com", "age": 10000}
register_user(**bad_form_data)

"""# Not only Field Type Validation but Data validation is also something
# which becomes important as you move towards defining Production systems
"""

name: str = "Aditi"
age: int = 28
price: float = 499.99
is_active: bool = True

print(name, age, price, is_active)

age: int = 'twenty-eight'

age

tags: list[str] = ["python", "pydantic", "fastapi"]
quantities: list[int] = [1, 5, 3, 2]
word_counts: dict[str, int] = {"error": 12, "warning": 5}
settings: dict[str, str] = {"theme": "dark", "language": "en"}

print(tags, quantities, word_counts, settings)

pip install pydantic



class FormData():
    def __init__(self, name, email, message):
        self.name = name
        self.email = email
        self.message = message

mayankForm = FormData(1234,'abc@gmail.com','I am going to travel')

"""# A plain class is not handling the type thing"""

from dataclasses import dataclass

@dataclass
class UserDataclass:
    name: str
    email: str
    age: int

mayankForm2 = UserDataclass('mayank','gadfa',4214)

from pydantic import BaseModel

class UserModel(BaseModel):
  name : str
  email:str
  age :int


user_pydantic = UserModel(name="Alice", email="alice@example.com", age="not a number")



# Optional vs Mandatory Field

from pydantic import BaseModel, ValidationError


class SignupForm(BaseModel):
    username: str
    email: str
    age: int
    newsletter_opt_in: bool = False   # has a default -> OPTIONAL field

incoming_data = {"username": "aditi28", "email": "aditi@example.com", "age": 28,"newsletter_opt_in":"True"}

user_a = SignupForm(**incoming_data)

user_a

Second_user = SignupForm(username='Mayank')



class SignupForm2(BaseModel):
  name : str
  age : int
  is_interested : bool

"""# Automatic Type Coerction"""

user_1_data = {"name": "mayank",  "age": "28" ,"is_interested":"True"}


user_1 = SignupForm2(**user_1_data)

user_1

user_2_data = {"name": "mayank",  "age": 28.5 ,"is_interested":True}

user_2 = SignupForm2(**user_2_data)

'28' -----> 28

'twenty eight' ----> Error



dump_data = user_1.model_dump()

dump_data

user_3_data = {"name": "mayank",  "age": 100000 ,"is_interested":True}
user_3 = SignupForm2(**user_3_data)











"""# Data Validation"""

from pydantic import BaseModel, Field


class JobApplicationV1(BaseModel):
    full_name: str = Field(min_length=2, max_length=100)
    years_experience: int = Field(ge=0, le=50)

job_data = {"full_name":"a","years_experience" :5}

JobApplicationV1(**job_data)

from typing import Annotated

class JobApplicationV1(BaseModel):
    full_name: str = Field(min_length=2, max_length=100)
    years_experience: int = Field(ge=0, le=50)
    email:str

class JobApplicationV2(BaseModel):
    full_name: Annotated[str, Field(min_length=2, max_length=100)]
    years_experience: Annotated[int, Field(ge=0, le=50)]

!pip install "pydantic[email]"

from pydantic import BaseModel, EmailStr, Field


class JobApplicationV3(BaseModel):
    full_name: str = Field(min_length=2, max_length=100)
    years_experience: int = Field(ge=0, le=50)
    email: EmailStr



from pydantic import *

class UserAccount(BaseModel):
    username: str
    password: SecretStr

account = UserAccount(username="rohan99", password="super-secret-123")
print(account)                              # password shows as **********
# print(account.password.get_secret_value())  # the real value, on purpose

account.model_dump()

import json

with open("account.json", "w") as f:
    json.dump(account.model_dump(mode="json"), f, indent=4)

class Applicant(BaseModel):
    name: str
    email: EmailStr

valid_applicant = Applicant(name="Rohan", email="rohan@yopmail.com")
print("Valid:", valid_applicant, "\n")



value = "abc@mayank-gs-india@yopmail.com"

value.split('@')[-1]

class JobApplication(BaseModel):
    full_name: str
    email: EmailStr
    years_experience: int =0


    @field_validator('email')
    @classmethod
    def reject_disposable_domains(cls,value:str)->str:

      blocked_domain = {'yopmail.com','tempmail.com','mailinator.com'}
      user_domain = value.split('@')[-1].lower()

      if user_domain in blocked_domain:
            raise ValueError(f"disposable email domains are not accepted ({user_domain})")

      return value.lower()

    @field_validator("years_experience")
    @classmethod
    def strip_years_suffix(cls, value):
        """
        Handles input like "5 years" or "5yrs" arriving as raw text —
        common when scraping form data or parsing free-text resumes —
        by stripping non-numeric junk BEFORE the int type-check runs.
        """
        if isinstance(value, str):
            digits_only = "".join(ch for ch in value if ch.isdigit())
            return int(digits_only) if digits_only else value
        return value

valid_applicant = JobApplication(full_name="Rohan", email="rohan@yopmail.com")
print("Valid:", valid_applicant, "\n")





class SignupForm(BaseModel):
    username: str
    password: str
    confirm_password: str


    @field_validator('password')
    @classmethod
    def reject_disposable_domains(cls,value:str)->str:
      if len(value)<8:
        raise ValidationError

      return value.lower()



    @field_validator('confirm_password')
    @classmethod
    def reject_disposable_domains(cls,value:str)->str:
      if len(value)<8:
        raise ValidationError

      return value.lower()

    @model_validator(mode="after")
    def passwords_must_match(self):
        """
        Cross-field rule: password and confirm_password must be
        identical. This is IMPOSSIBLE to express with field_validator
        alone, because a single field_validator only ever sees one
        field's value — it has no visibility into any other field.
        """
        if self.password != self.confirm_password:
            raise ValueError("password and confirm_password do not match")
        return self

SignupForm(username="rohan99", password="abcdef123", confirm_password="abcdef123")







class SignupForm(BaseModel):
    username: str
    password: str
    confirm_password: str
    height : int
    weight: int







class JobApplication(BaseModel):
    full_name: str
    years_experience: int


    @computed_field
    @property
    def experience_tier(self) -> str:
      if self.years_experience <2:
        return 'junior'

      elif self.years_experience <7  :
        return 'mid'

      return 'senior'

app = JobApplication(full_name="Aditi Sharma", years_experience=6)

app

app.full_name,app.experience_tier







from pydantic import BaseModel

class Address(BaseModel):
    city: str
    state: str
    pin_code: str = Field(gt=1000,lt=43125315)



class Applicant(Address):
    name: str
    email: str
    address: Address

