# -*- coding: utf-8 -*-
"""Runtime and HITL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFuLlELzyS2NDIBgeVOowrqGJGFPERSL

# Runtime
"""

!pip install -U "langchain>=1.3.14"

!pip install  langchain-openai langchain-community langgraph python-dotenv langchain-mcp-adapters langchain-chroma chromadb pypdf

!pip install langchain-anthropic

import os
from dotenv import load_dotenv
load_dotenv()

from google.colab import userdata
os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')

from langchain.chat_models import init_chat_model

model = init_chat_model('openai:gpt-5-mini')
model.invoke('Hi')
print("Cinebot's Brain is connected")

from langchain.chat_models import init_chat_model
from langchain.agents import create_agent, AgentState
from langchain_core.tools import tool
from langchain.tools import tool as tool_rt, ToolRuntime
from dataclasses import dataclass

@dataclass
class CineBotContext:
  user_name:str
  #geo_state:str # Delhi or Bangalore or Chennai

agent_with_context = create_agent(
    model="openai:gpt-5-mini",
    tools=[],
    context_schema=CineBotContext,   # declares the SHAPE of context this agent expects
)

result = agent_with_context.invoke(
    {"messages": [{"role": "user", "content": "What's my name?"}]},
    context=CineBotContext(user_name="Priya"),   # injected at invocation time
)



"""# Runtime Inside Tools : ToolRuntime"""

@dataclass
class CustomerContext:
  user_id:str

from langgraph.store.memory import InMemoryStore

loyalty_store=InMemoryStore()

@tool
def fetch_customer_preferences(runtime: ToolRuntime[CustomerContext])-> str:
  "Feth the customer's Saved Preferences from a long term Memory"
  user_id=runtime.context.user_id
  preferences = "No Preferences"

  if runtime.store:
    if memory := runtime.store.get(('users'),user_id):
      preferences = memory.value['preferences']

  return preferences

pref_agent = create_agent(
    model="openai:gpt-5-mini",
    tools=[fetch_customer_preferences],
    context_schema=CustomerContext,
    store=loyalty_store,
)



"""# MiddleWare"""

#NodeStyle ( Before_model, after_model)
# Wrap_style_hooks ( wrap_model_call)

"""# Node Style Hooks"""

from langchain.agents.middleware import before_model, after_model

@before_model
def log_before_model(a,b):
  pass

logged_agent = create_agent(model="openai:gpt-5-mini", tools=[fetch_customer_preferences], middleware=[log_before_model])

result = logged_agent.invoke({"messages": [("user", "Get user preferences")]})



"""# Wrap Style Hooks"""

from langchain.agents.middleware import wrap_model_call, ModelRequest, ModelResponse
from typing import Callable

@wrap_model_call
def dynamic_greeting_prompt(request: ModelRequest,handler: Callable[[ModelRequest], ModelResponse])->ModelResponse:
  response = handler(request)
  return response

wrap_style_agent = create_agent(
    model="openai:gpt-5-mini",
    tools=[],
    middleware=[dynamic_greeting_prompt],
    context_schema=CineBotContext,
)

result = wrap_style_agent.invoke(
    {"messages": [("user", "What should I call you, and who am I?")]},
    context=CineBotContext(user_name="Rohan"),
)



"""# Dynamic Prompting"""

from langchain.agents.middleware import dynamic_prompt

@dataclass
class ClaudeContext:
  user_specific_instructions: str

@dynamic_prompt
def personalize_the_prompt(request:ModelRequest):
  user_name = request.runtime.context.user_name
  return f"{Claude_Instructions} + {request.runtime.context.user_specific_instructions}"

@before_model
def auth_gate(state:AgentState,runtime:Runtime)-> dict|None:
  "Block Unauthenticated users"
  server = runtime.server_info
  if server is not None:
    raise ValueError("Unauthenticated User")

  print(f"[AUTH] Passed the check for user {runtime.context.user_name} and threadID {runtime.execution_info.thread_id}")



"""# Human in the Loop ( In Depth )"""

from langchain.chat_models import init_chat_model
from langchain.agents import create_agent
from langchain_core.tools import tool
from langchain.agents.middleware import HumanInTheLoopMiddleware
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.types import Command
model = init_chat_model("openai:gpt-5-mini")

from rich import print

@tool
def cancel_booking(booking_id: str,runtime:ToolRuntime) -> str:
    """Cancel an existing booking. Irreversible."""
    return f"Booking {booking_id} cancelled."

unguarded_agent = create_agent(model="openai:gpt-5-mini", tools=[cancel_booking])
result = unguarded_agent.invoke({"messages": [("user", "Cancel my booking BK1042")]})

print(result)

result = unguarded_agent.invoke({"messages": [("user", "Hi I am Mayank")]})

print(result)

result = unguarded_agent.invoke({"messages": [("user", "Who am I?")]})

print(result)

result.interrupts

@tool
def send_booking_confirmation(booking_id: str, email: str) -> str:
    """Send a booking confirmation email. Safe, no approval needed."""
    return f"Confirmation for {booking_id} sent to {email}."

guarded_agent = create_agent(
    model="openai:gpt-5-mini",
    tools=[cancel_booking, send_booking_confirmation],
    middleware=[
        HumanInTheLoopMiddleware(
            interrupt_on={
                "cancel_booking": True,               # all four decisions allowed (default config)
                "send_booking_confirmation": False,    # safe operation, auto-approved, never pauses
            },
            description_prefix="CineBot action pending your approval",
        ),
    ],
    checkpointer=InMemorySaver(),   # REQUIRED -- HITL needs to pause and later resume
)

config = {"configurable": {"thread_id": "hitl-demo-111"}}



result = guarded_agent.invoke(
    {"messages": [("user", "Cancel booking BK1042")]},
    config=config,
    version="v2",   # the current, recommended invoke pattern for reading interrupts
)

print(result)

result.interrupts

"""# Command"""

resumed = guarded_agent.invoke(
    Command(
        resume={"decisions": [{"type": "approve"}]}  # or "reject"
    ),
    config=config, # Same thread ID to resume the paused conversation
    version="v2",
)

print(resumed)

"""# Edit"""

resumed_edit = guarded_agent.invoke(
    Command(resume={"decisions": [{
        "type": "edit",
        "edited_action": {"name": "cancel_booking", "args": {"booking_id": "BK1042"}},
    }]}),
    config=config2, version="v2",
)

config3 = {"configurable": {"thread_id": "hitl-demo-3"}}
guarded_agent.invoke({"messages": [("user", "Cancel booking BK1042")]}, config=config3, version="v2")

resumed_reject = guarded_agent.invoke(
    Command(resume={"decisions": [{
        "type": "reject",
        "message": "Cancellations require manager sign-off first. Ask the customer to call support.",
    }]}),
    config=config3, version="v2",
)

print(resumed_reject.value["messages"][-1].content)



@tool
def ask_customer(question: str) -> str:
    """Ask the customer a clarifying question and wait for their reply."""
    return "placeholder -- never actually reached, respond intercepts this"

ask_agent = create_agent(
    model="openai:gpt-5-mini",
    tools=[ask_customer],
    middleware=[HumanInTheLoopMiddleware(interrupt_on={"ask_customer": {"allowed_decisions": ["respond"]}})],
    checkpointer=InMemorySaver(),
)

config_ask = {"configurable": {"thread_id": "hitl-demo-3"}}

ask_agent.invoke({"messages": [("user", "Cancel booking BK1042")]}, config=config_ask)

resumed_agent_respond = ask_agent.invoke(
    Command(resume={"decisions": [{
        "type": "respond",
        "message": "Its Booking BK1042, for the movie interstellar",
    }]}),
    config=config_ask
)

print(resumed_agent_respond)



"""# Conditional Interrupts"""

from langchain.agents.middleware import ToolCallRequest

@tool
def cancel_booking_priced(booking_id: str, amount: float) -> str:
    """Cancel a booking with a refund amount."""
    return f"Booking {booking_id} cancelled, ${amount:.2f} refunded."

ToolCallRequest
'''
    tool_call: ToolCall
    tool: BaseTool | None
    state: Any
    runtime: ToolRuntime
'''

def is_large_refund(request: ToolCallRequest)-> bool:
  # amount = request.tool_call['args'].get('amount',0)
  # return amount >100
  return True

conditional_agent = create_agent(
    model="openai:gpt-5-mini",
    tools=[cancel_booking_priced],
    middleware=[
        HumanInTheLoopMiddleware(
            interrupt_on={
                "cancel_booking_priced": {
                    "allowed_decisions": ["approve", "edit", "reject"],
                    "when": is_large_refund,
                },
            },
        ),
    ],
    checkpointer=InMemorySaver(),
)

config_small = {"configurable": {"thread_id": "small-refund"}}
r_small = conditional_agent.invoke(
    {"messages": [("user", "Cancel booking BK1001, refund $25")]}, config=config_small
)
print("Small refund, paused?", bool(r_small.interrupts))

print(r_small)



config_large = {"configurable": {"thread_id": "large-refund"}}
r_large = conditional_agent.invoke(
    {"messages": [("user", "Cancel booking BK1002, refund $500")]}, config=config_large, version="v2",
)
print("Large refund, paused?", bool(r_large.interrupts))

print(r_large)



def run_interactive_hitl(agent, config):
    """A real, interactive HITL loop -- uses the CORRECTED edited_action format."""
    result = agent.invoke({"messages": [("user", "Cancel booking BK1042")]}, config=config, version="v2")
    if not result.interrupts:
        print("Nothing paused for review.")
        return

    print("CineBot wants to cancel booking BK1042. Choose a decision:")
    print("  1) approve")
    print("  2) edit     -- cancel a DIFFERENT booking ID instead")
    print("  3) reject")
    choice = input("Type 1, 2, or 3: ").strip()

    if choice == "1":
        decision = {"type": "approve"}
    elif choice == "2":
        new_id = input("Booking ID to cancel instead: ").strip()
        decision = {"type": "edit", "edited_action": {"name": "cancel_booking", "args": {"booking_id": new_id}}}
    elif choice == "3":
        reason = input("Reason: ").strip()
        decision = {"type": "reject", "message": reason}
    else:
        print("Not a valid choice.")
        return

    resumed = agent.invoke(Command(resume={"decisions": [decision]}), config=config, version="v2")
    print()
    print("Final:", resumed.value["messages"][-1].content)

run_interactive_hitl(guarded_agent, {"configurable": {"thread_id": "live-interactive-demo3"}})

