# -*- coding: utf-8 -*-
"""Python Refresher & Pydantic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10u_Rae677OnKyOkgAS72gr2gyMNKcqSm
"""

# --- Dictionaries: labeled data, accessed by key instead of position ---
weather_reading = {
    "city": "Tokyo",
    "temperature_c": 22.5,
    "condition": "partly cloudy",
}


print(weather_reading["city"])          # access by key
print(weather_reading.get("humidity"))  # .get() -- returns None instead of crashing if missing
weather_reading["humidity"] = 60        # adding a new key
print(weather_reading)

for key,value in weather_reading.items():
  print (key,"------------>",value)

for key, value in weather_reading.items():   # looping over BOTH keys and values
    print(f"{key}: {value}")

# --- The combination that matters most: a list of dictionaries ---
readings = [
    {"city": "Tokyo", "temperature_c": 22.5},
    {"city": "Delhi", "temperature_c": 34.0},
    {"city": "London", "temperature_c": 15.0},
]
for reading in readings:
    print(f"{reading['city']}: {reading['temperature_c']}°C")

warm_cities = [r["city"] for r in readings if r["temperature_c"] > 20]   # a list comprehension
print(f"Warm cities: {warm_cities}")



Bank Account

ba1=123
ba2=234
ba3=345



class BankAccount:
    """A blueprint for a bank account -- nothing to do with AI."""

    def __init__(self, owner: str, balance: float = 0.0):
        self.owner = owner       # every instance gets its OWN owner
        self.balance = balance   # and its OWN balance -- this is the account's STATE
        self.history = []        # a list, just like File 1's data structures

    def deposit(self, amount: float) -> None:
        self.balance += amount
        self.history.append(f"Deposited {amount}")

    def withdraw(self, amount: float) -> None:
        if amount > self.balance:
            print(f"Insufficient funds: tried to withdraw {amount}, balance is {self.balance}")
            return
        self.balance -= amount
        self.history.append(f"Withdrew {amount}")

    def show_history(self) -> None:
        for entry in self.history:
            print(f"  - {entry}")

account_1 = BankAccount(owner="Mayank", balance=1000)
account_2 = BankAccount(owner="Krish", balance=50000)







result = 10 / 0

# --- Without error handling, ANY unexpected problem stops everything. ---
# (Read, don't run, this comment: result = 10 / 0 would crash the whole
# program with a ZeroDivisionError.)

# --- try/except: catch it, decide what happens instead ---
try:
    result = 10 / 0
except ZeroDivisionError:
    print("Can't divide by zero -- using 0 instead.")
    result = 0
print(f"result is now: {result}")

age = '53513'

# --- A different failure, same shape ---
try:
    age = int("not a number")
except ValueError:
    print("That wasn't a valid number -- using 0 instead.")
    age = 0
print(f"age is now: {age}")







# --- Catching more than one possible problem ---
def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return 0
    except TypeError:
        return 0

print(safe_divide(10, 2), safe_divide(10, 0), safe_divide(10, "x"))

"""
_3_error_handling.py

try/except -- catching a problem on purpose instead of letting it crash
your entire program. Still no AI, no agents.

Run with: uv run _3_error_handling.py
"""




# --- finally: runs no matter what happened ---
def read_setting(value):
    try:
        return int(value)
    except ValueError:
        print(f"{value!r} isn't a number, defaulting to 0.")
        return 0
    finally:
        print("(Done attempting to read this setting.)")

read_setting("42")
read_setting("oops")

# --- Tying it back to File 1's data structures: a missing dict key ---
weather_reading = {"city": "Tokyo", "temperature_c": 22.5}
try:
    print(weather_reading["humidity"])   # this key doesn't exist
except KeyError:
    print("No humidity data available -- that's fine, we'll skip it.")


if __name__ == "__main__":
    print("\nError handling done. Every risky operation above was caught -- nothing crashed.")









import functools
import time

def decorator(func):
    def wrapper():
        print("Before calling the function.")
        func()
        print("After calling the function.")
    return wrapper

def greet():
    print("Hi I am the Greet Function")
    print("Hello, World!")
greet()

print(decorator(greet)())

def myNoReturnFunction(name):
  pass


myNoReturnFunction('Mayank')

@decorator
def greet():
    print("Hello, World!")


#### Decroator(greet) ----------> wrapper()



# this gives you the wrapper() as the output which then is ran and give you final output

def announce(func):
    """Announces when a function starts and finishes."""

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        print(f"Starting {func.__name__}...")
        result = func(*args, **kwargs)
        print(f"Finished {func.__name__}.")
        return result

    return wrapper


@announce
def greet(name):
    return f"Hello, {name}!"


print(greet("Mayank"))

def slow_addition(a, b):
    time.sleep(0.05)
    return a + b


print(slow_addition(3, 4))

def timer(func):
    """Prints the runtime of the decorated function."""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        start_time = time.perf_counter()
        value = func(*args, **kwargs)
        end_time = time.perf_counter()
        run_time = end_time - start_time
        print(f"Finished {func.__name__!r} in {run_time:.4f} secs")
        return value
    return wrapper


@timer
def slow_addition(a, b):
    time.sleep(0.05)
    return a + b


print(f"Result: {slow_addition(3, 4)}")
print(f"Result: {slow_addition(5, 6)}")



import time


def slow_addition(a, b):
    time.sleep(0.05)  # Pause for 50 milliseconds
    return a + b


start = time.perf_counter()      # Start timer
result = slow_addition(3, 4)
end = time.perf_counter()        # Stop timer

print(result)
print(f"Time taken: {end - start:.6f} seconds")





def timed(func):
    """Prints how long a function took to run."""

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        start = time.perf_counter()
        result = func(*args, **kwargs)
        elapsed_ms = (time.perf_counter() - start) * 1000
        print(f"{func.__name__} took {elapsed_ms:.2f} ms")
        return result

    return wrapper


@timed
def slow_addition(a, b):
    time.sleep(0.05)
    return a + b


print(slow_addition(3, 4))









import requests

# --- The simplest possible request ---
response = requests.get(
    "https://api.frankfurter.dev/v1/latest",
    params={"base": "USD", "symbols": "INR"},
    timeout=10,   # never call a real API with no timeout
)

response.json()





# --- Wrapped in a reusable function, with error handling from File 3 ---
@timed
def convert_currency(amount: float, from_currency: str, to_currency: str) -> float | str:
    """Convert `amount` between currencies using real, live ECB rates."""
    try:
        response = requests.get(
            "https://api.frankfurter.dev/v1/latest",
            params={"base": from_currency.upper(), "symbols": to_currency.upper()},
            timeout=10,
        )
        response.raise_for_status()
        print(response.json())

        rate = response.json()["rates"][to_currency.upper()]
        return round(amount * rate, 2)
    except requests.exceptions.RequestException as exc:
        return f"Couldn't reach the currency service: {exc}"
    except KeyError:
        return f"No rate available for {from_currency} -> {to_currency}"

print(convert_currency(100, "USD", "INR"))







def fake_ai(model, max_tokens, messages):
    # Get the last user message
    user_message = messages[-1]["content"].lower()
    print(user_message)
    # Simple rule-based replies
    if "currency" in user_message or "convert" in user_message:
        reply = "I'd use a currency conversion tool instead of guessing."

    elif "weather" in user_message:
        reply = "I'd use a weather tool to check the latest weather."

    else:
        reply = "I'm just a fake AI. I'm using simple if-else rules."

    # Return data in the same format as a real AI API
    return {
        "choices": [
            {
                "message": {
                    "content": reply
                }
            }
        ]
    }

questions = [
    "Convert 50 dollars to euros.",

]

for question in questions:
    response = fake_ai(
        model="fake-model",
        max_tokens=200,
        messages=[
            {
                "role": "user",
                "content": question
            }
        ]
    )

    print(f"User: {question}")
    print(f"Stand-in: {response['choices'][0]['message']['content']}\n")

# Pydantic

# Python is Dynamically Typed Langauge

name = 'Mayank'

name = 8

def create_user(name:str, age:int):
    print(f"Name: {name}")
    print(f"Age next year: {age }")

create_user('Mayank',[1,2,3,4,5,6,6,7])

create_user('Mayank','fifteen')

"""
We can check types ourselves...
"""


def create_user(name, age):

    if not isinstance(name, str):
        raise TypeError("name must be a string")

    if not isinstance(age, int):
        raise TypeError("age must be an integer")

    print(f"{name} is {age} years old.")

def create_user(name, age):
    """
    Creates a user, attempting to convert age to an integer if it's a string.
    Raises TypeError if name is not a string or if age cannot be converted to an integer.
    """
    if not isinstance(name, str):
        raise TypeError("name must be a string")

    # Attempt to convert age to an integer if it's a string
    if isinstance(age, str):
        try:
            age = int(age)
        except ValueError:
            raise TypeError("age must be an integer or a string that can be converted to an integer")
    elif not isinstance(age, int):
        # If it's not a string and not an int, it's an invalid type
        raise TypeError("age must be an integer")

    print(f"{name} is {age} years old.")

create_user("Mayank", 25)

create_user("Rahul", "25")

import pydantic

from pydantic import BaseModel

class User(BaseModel):
  name : str
  age:int

user = User(
    name="Rahul",
    age=25
)

def create_user(newUser:User):
    print(f"Name: {newUser.name}")
    print(f"Age next year: {newUser.age }")

mayank = User(
    name='Mayank',
    age=25
)

create_user(mayank)

mayank2 = User(
    name='Mayank2',
    age='twenty-five'  # Pydantic does type conversion
)

create_user(mayank2)

mayank3 = User(
    name='Mayank3',
    age= -5
)